@URL = http://localhost:3000
@serviceUrl = {{URL}}/api/services

###
# Get all
GET {{serviceUrl}}

###
# Get by id
GET {{serviceUrl}}/1

###
# Add
POST {{serviceUrl}}
Content-Type: application/json

{
  "name": "Sport massage 1 hour",
  "price": 65,
  "category": {
    "name": "massage"
  }
}

###
# Update
PUT {{serviceUrl}}/2
Content-Type: application/json

{
  "price": 65
}

###
# Delete
DELETE {{serviceUrl}}/3

###
# Book a service
POST {{serviceUrl}}/199/book
Content-Type: application/json

{
  "name": "John Doe",
  "email": "{{$dotenv TEST_SENDER_EMAIL}}",
  "mobile": "1234567890",
  "selectedTime": "Tue Dec 03 2024 09:00:00 GMT 0200 (Eastern European Standard Time)"
}

###############################################
#### Test ####

###
# Add with wrong format
POST {{serviceUrl}}
Content-Type: application/json

{
  "name": "Sport massage 1 hour",
  "price": 65,
  "category": "massage"
}